### PR TITLE
Display

### PR DESCRIPTION
**Pull request by CallumCM**
Adds a chip that contains an 8x8 display, you select a pixel with the address and another bit for whether it's on. It is currently only black and white, but more configurability for this chip will be added in the future.

### CODE REVIEW

**Comment by CallumCM** [comment]
Added 2-bit RGB color

**Comment by AOx0** [comment]
Omg I did not notice, sorry

**Comment by AOx0** [comment]
May I merge misc-features or only up to Display? @Turnip1234

**Comment by CallumCM** [comment]
You can do whatever you want. So yes, go ahead!

**Comment by CallumCM** [comment]
> Omg I did not notice, sorry

No worries!

**Comment by FunkyEgg** [comment]
cant wait for the new ver with the settings :D

**Comment by AOx0** [comment]
Finally merged this :'D (sorry)

**Pull request merged**
